M48
; DRILL file {KiCad 6.0.1-79c1e3a40b~116~ubuntu21.04.1} date Tue 15 Feb 2022 03:37:34 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-02-15T15:37:34-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.1-79c1e3a40b~116~ubuntu21.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X79.61Y-62.56
T0
M30
